# Global settings applied to the whole site.
[build]
  command = "yarn pre-build && yarn build"

[functions]
  included_files = ["content/**/*"]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]

[context.2017]
  publish = "_site"
  command = "gulp compile --env production"

[context.2015]
  publish = "_site"
  command = "gulp && bundle exec jekyll build"
