import '../stylesheets/main.sass'
import type { Metadata } from 'next'
import { ReactNode } from 'react'
import Header from '@/components/header'
import Footer from '@/components/footer'
import Menu from '@/components/menu'
import Contact from '@/components/contact'
import Title from '@/components/title'

export const metadata: Metadata = {
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
  menu: ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <Title />
      </head>
      <body>
        <Header />
        <Menu />
        {children}
        <Footer />
        <Contact />
      </body>
    </html>
  )
}
