import '@/stylesheets/main.sass'
import type { Metadata } from 'next'
import { PropsWithChildren } from 'react'
import Header from '@/components/header'
import Footer from '@/components/footer'
import Menu from '@/components/menu'
import Contact from '@/components/contact'
import Title from '@/components/title'
import WebmentionsHead from '@/components/webmentions-head'
import Accounts from '@/components/accounts'
import Main from '@/components/main'

export const metadata: Metadata = {
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren<{}>) {
  return (
    <html lang="en">
      <head>
        <Accounts />
        <WebmentionsHead />
        <Title />
      </head>
      <body>
        <Header />
        <Menu />
        {/*<Main>{children}</Main>*/}
        {children}
        <Footer />
        <Contact />
      </body>
    </html>
  )
}
